#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May  3 17:37:12 2020

@author: mc4117
"""

import pandas as pd

df_real = pd.read_csv('fixed_output/160_bed_trench_output.csv')
df_test1 = pd.read_csv('adapt_output2/bed_trench_output0.2_200.0.csv')
df_test2 = pd.read_csv('adapt_output2/bed_trench_output0.4_200.0.csv')
df_test3 = pd.read_csv('adapt_output2/bed_trench_output0.6_200.0.csv')
df_test4 = pd.read_csv('adapt_output2/bed_trench_output0.8_200.0.csv')
df_test5 = pd.read_csv('adapt_output2/bed_trench_output1.0_200.0.csv')

error_list = []
error_list.append(sum([(df_test1['bath'][i] - df_real['bath'][i])**2 for i in range(len(df_real))]))
error_list.append(sum([(df_test2['bath'][i] - df_real['bath'][i])**2 for i in range(len(df_real))]))
error_list.append(sum([(df_test3['bath'][i] - df_real['bath'][i])**2 for i in range(len(df_real))]))
error_list.append(sum([(df_test4['bath'][i] - df_real['bath'][i])**2 for i in range(len(df_real))]))
error_list.append(sum([(df_test5['bath'][i] - df_real['bath'][i])**2 for i in range(len(df_real))]))
#error_list.append(sum([(df_test6['bath'][i] - df_real['bath'][i])**2 for i in range(len(df_real))]))
#error_list.append(sum([(df_test7['bath'][i] - df_real['bath'][i])**2 for i in range(len(df_real))]))